migrate bot to typescript
Joystream/community-repo pull request #36
Opened 2020-10-25 18:16 UTC by traumschule

See #23

2020-10-27 10:32 UTC, freakstatic commented
I did a quick review and it seems very good!
Good job :)

2020-10-28 19:02 UTC, mochet commented
This was approved by the council here: https://testnet.joystream.org/#/proposals/32

2020-10-30 07:53 UTC, bwhm commented
@DzhideX 
Do you mind having a look at the code? I'm running some tests now, but it would be nice if you could have a closer look :)

2020-10-30 14:26 UTC, DzhideX requested changes
Hi @traumschule,

this is really good but I have some small remarks that should be fixed.The two changes in `bot.ts` and `config.ts` are vital whereas the rest are mostly cosmetic. 

After you've made all of the changes it would be nice if you could just delete all of the unused imports, variables, commented out logic as well.

Thank you for your contribution :100:

2020-10-30 14:26 UTC, DzhideX commented on community-contributions/joystreamtelegrambot/config.ts
> +// websocket location
I don't know if this is something just on my side here but running the bot I'd get this: 

```
2020-10-30 12:14:38          API-WS: disconnected from ws://rome-rpc-endpoint.joystream.org:9944/ code: '1006' reason: 'connection failed'
```

Changing `ws` to `wss` seems to fix it.

This is nitpicking but maybe also move the comment above the declaration? :)

2020-10-30 14:26 UTC, DzhideX commented on community-contributions/joystreamtelegrambot/src/bot.ts
> +    //bot.sendMessage(chatid, msg, { parse_mode: "HTML" });
I assume this is not supposed to be commented out?

2020-10-30 14:26 UTC, DzhideX commented on community-contributions/joystreamtelegrambot/src/lib/announcements.ts
> +  let result: any = await callback();
Result will implicitly figure out the type to be any here, no need to explicitly write it. 

There's more similar situations in the files.

2020-10-30 14:26 UTC, DzhideX commented on community-contributions/joystreamtelegrambot/src/lib/getters.ts
> +  const id: number = await api.query.members.memberIdsByRootAccountId(account);
I think we can use `MemberId` here, unless there's a reason not to?

There are also some necessary changes on line 23, 103 and announcements.ts

2020-11-01 14:30 UTC, bwhm commented
As we didn't complete the review in time, this will be graded as fully implemented, ref [this](https://github.com/Joystream/community-repo/issues/23). 
Although there is no indication that the third success event (see below) is fixed, the full amount is paid.
```
The 'bug' associated with the finalization of Proposals are fixed 
```

I will merge it now, but we will perform a few small fixes.

2020-11-01 14:30 UTC, merged