Add Giza council 43 reports
Joystream/community-repo pull request #678
Opened 2022-02-17 16:15 UTC by Ilichhh

2022-02-20 16:33 UTC, traumschule requested changes
nice [find](https://discord.com/channels/811216481340751934/812343711870091285/944970047598764033) @mochet

2022-02-20 16:33 UTC, traumschule commented on council/tokenomics/giza/Council_Round43_4395600-4496399_Tokenomics_Report.md
> +| Number of  Workers | 9 | 8 | 0 |
with [c5b328696185f8bc0b4c13ec78372337896d7405](https://github.com/Joystream/community-repo/pull/601/commits/c5b328696185f8bc0b4c13ec78372337896d7405)
> ### 4.2 Curators
> | Number of  Workers | 9 | 8 | -11.11 |

2022-02-20 16:33 UTC, traumschule commented on council/tokenomics/giza/Council_Round43_4395600-4496399_Tokenomics_Report.md
> +| Number of  Workers | 30 | 24 | 0 |
with [c5b328696185f8bc0b4c13ec78372337896d7405](https://github.com/Joystream/community-repo/pull/601/commits/c5b328696185f8bc0b4c13ec78372337896d7405)
> ### 4.5 Operations
> | Number of  Workers | 30 | 24 | -20 |

2022-02-20 16:33 UTC, traumschule commented on council/tokenomics/giza/Council_Round43_4395600-4496399_Tokenomics_Report.md
> +| Number of  Workers | 11 | 14 | 27.27 |
with [c5b328696185f8bc0b4c13ec78372337896d7405](https://github.com/Joystream/community-repo/pull/601/commits/c5b328696185f8bc0b4c13ec78372337896d7405)
> ### 4.4 Distribution
> | Number of  Workers | 10 | 13 | 30 |

2022-02-21 08:17 UTC, igrexac commented
[Proposal](https://testnet.joystream.org/#/proposals/1182) approved

2022-02-25 13:10 UTC, traumschule approved these changes
LGTM!

2022-02-25 13:38 UTC, freakstatic approved these changes
LGTM!

2022-02-25 13:39 UTC, freakstatic approved these changes

2022-02-25 14:12 UTC, traumschule commented on council/tokenomics/giza/Council_Round43_4395600-4496399_Tokenomics_Report.md
> +### 4.7 Gamma
ok

2022-02-25 14:13 UTC, merged